# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Ayu Mirage by Khue Nguyen <Z5483Y@gmail.com>

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#171B24"
idle_fg = "#CCCAC2"
info_bg = "#95E6CB"
info_fg = "#171B24"
good_bg = "#D5FF80"
good_fg = "#171B24"
warning_bg = "#FFD173"
warning_fg = "#171B24"
critical_bg = "#F28779"
critical_fg = "#171B24"
# The rest of the theme settings are left at default.
