# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Rosé Pine Moon by Emilia Dunfelt <sayhi@dunfelt.se>

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#232136"
idle_fg = "#e0def4"
info_bg = "#3e8fb0"
info_fg = "#232136"
good_bg = "#ea9a97"
good_fg = "#232136"
warning_bg = "#f6c177"
warning_fg = "#232136"
critical_bg = "#ecebf0"
critical_fg = "#232136"
# The rest of the theme settings are left at default.
